Feat: Adding docker support.

diff --git a/.github/workflows/build_test_react.yml b/.github/workflows/build_test_react.yml
--- a/.github/workflows/build_test_react.yml
+++ b/.github/workflows/build_test_react.yml
@@ -137,6 +137,68 @@ jobs:
       #   env:
       #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
+  docker-test:
+    needs: publish-npm
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build mysql image
+        run: docker build -t test-migration .  
+
+      - name: Build API image
+        run: docker build -t user_api -f python.Dockerfile .
+
+      - name: Start MySQL container
+        run: |
+          docker run -d \
+            --name mysql-test \
+            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
+            -p 3306:3306 \
+            test-migration
+
+      - name: Wait for MySQL
+        run: |
+          echo "Waiting for MySQL..."
+          for i in {1..30}; do
+            docker exec test-migration mysqladmin ping -h "host.docker.internal" --silent && break
+            sleep 2
+          done
+
+      - name: Start API container
+        run: |
+          docker run -d \
+            --name api-test \
+            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
+            -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
+            -e MYSQL_HOST=host.docker.internal \
+            -p 8000:8000 \
+            user_api
+
+      - name: Test /users endpoint
+        run: |
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" http://localhost:8000/users)
+          echo "HTTP response code: $RESPONSE"
+          if [ "$RESPONSE" != "200" ]; then
+            echo "API /users endpoint failed"
+            exit 1
+          fi
+      
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
+
+      - name: Push API image to Docker Hub
+        run: |
+          docker tag test-api ${{ secrets.DOCKER_USERNAME }}/user_api:latest
+          docker tag test-migration ${{ secrets.DOCKER_USERNAME }}/migration_mysql:latest
+
+          docker push ${{ secrets.DOCKER_USERNAME }}/user_api:latest
+          docker push ${{ secrets.DOCKER_USERNAME }}/migration_mysql:latest
+
   deploy:
     needs: publish-npm
     permissions:
