Fix: add environment variables for JWT and update FastAPI routes for user authentication and deletion

diff --git a/.github/workflows/build_test_react.yml b/.github/workflows/build_test_react.yml
--- a/.github/workflows/build_test_react.yml
+++ b/.github/workflows/build_test_react.yml
@@ -146,6 +146,8 @@ jobs:
       MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
       MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
       MYSQL_USER: ${{ secrets.MYSQL_USER }}
+      MY_SECRET: ${{ secrets.MY_SECRET }}
+      ALGORITHM: HS256
 
     steps:
       - name: Checkout repository
@@ -166,6 +168,15 @@ jobs:
       - name: Test /users endpoint
         run: |
           RESPONSE=$(curl -s -o response.json -w "%{http_code}" 172.17.0.1:8000/users)
+          echo "HTTP response code: $RESPONSE"
+          if [ "$RESPONSE" != "200" ]; then
+            echo "API /users endpoint failed"
+            exit 1
+          fi
+
+      - name: Test Frontend in Docker
+        run: |
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" 172.17.0.1:3000)
           echo "HTTP response code: $RESPONSE"
           if [ "$RESPONSE" != "200" ]; then
             echo "API /users endpoint failed"
